"""
SentinelAI - MITRE Mapper
Maps identified threats to MITRE ATT&CK tactics and techniques.
"""

class MITREMapper:
    def __init__(self):
        self.mappings = {
            "phishing": {
                "tactic_id": "TA0001",
                "tactic_name": "Initial Access",
                "phase": "Delivery",
                "description": "Adversaries may send phishing messages to gain access to victim systems.",
                "mitigations": ["User Training", "Email Filtering", "Antivirus"]
            },
            "url_malicious": {
                "tactic_id": "TA0001",
                "tactic_name": "Initial Access",
                "phase": "Delivery",
                "description": "Adversaries may use malicious URLs to deliver malware or harvest credentials.",
                "mitigations": ["Web Proxies", "Domain Blacklisting", "Network Intrusion Prevention"]
            },
            "deepfake": {
                "tactic_id": "TA0001",
                "tactic_name": "Initial Access",
                "phase": "Reconnaissance / Exploitation",
                "description": "Synthetic media used for impersonation or social engineering.",
                "mitigations": ["Identity Verification", "Media Provenance", "Face Liveness Detection"]
            },
            "behaviour_anomaly": {
                "tactic_id": "TA0007",
                "tactic_name": "Discovery",
                "phase": "Post-Exploitation",
                "description": "Unusual activity patterns suggesting discovery or lateral movement.",
                "mitigations": ["User Account Management", "Behavioral Analytics", "Privilege Escalation Prevention"]
            },
            "prompt_injection": {
                "tactic_id": "TA0002",
                "tactic_name": "Execution",
                "phase": "In-system Exploitation",
                "description": "Malicious prompts designed to bypass AI guardrails or execute unauthorized commands.",
                "mitigations": ["Input Sanitization", "Prompt Filtering", "Output Validation"]
            },
            "ai_generated": {
                "tactic_id": "TA0005",
                "tactic_name": "Defense Evasion",
                "phase": "Persistence",
                "description": "Content likely generated by AI to bypass traditional static analysis.",
                "mitigations": ["Stylometric Analysis", "AI Content Detection", "Consistency Checks"]
            }
        }

    def get_mapping(self, threat_type: str) -> dict:
        return self.mappings.get(threat_type, {
            "tactic_id": "N/A",
            "tactic_name": "General Security",
            "phase": "Unknown",
            "description": "General threat detected by SentinelAI multi-model engine.",
            "mitigations": ["Standard Security Controls", "Monitoring"]
        })

mitre_mapper = MITREMapper()
